# Use root/example as user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: biblioteca_bd
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data